language: c
compiler :
  - clang
  - gcc
sudo: true
install: sudo apt-get install check
before_script:
  - cmake --version
  - cmake CMakeLists.txt
  - cmake .
script:
  - gcc -g test_main.c -o spell_test `pkg-config --cflags --libs check`
  - ./spell_test
  - gcov spell_test.c