language: c
compiler :
  - clang
  - gcc
sudo: true
install: sudo apt-get install check
before_script:
  - cmake --version
  - cmake CMakeLists.txt
  - cmake .
script:
  - make
  - gcc -coverage -O0 test_main.c -o spell_test
  - ./spell_test
  - gcov spell_test.c